Output After Training:
[[0.00967022 0.00967012 0.00967177 0.00967097]
 [0.00786296 0.00786136 0.00786459 0.00786399]
 [0.99359177 0.9935933  0.99359037 0.99359086]
 [0.9921162  0.99211658 0.99211487 0.99211551]]


In [14]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# input dataset
X = np.array([  [0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])

# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1

for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
print ("Output After Training:")
print (l1)

Output After Training:
[[0.00967022 0.00967012 0.00967177 0.00967097]
 [0.00786296 0.00786136 0.00786459 0.00786399]
 [0.99359177 0.9935933  0.99359037 0.99359086]
 [0.9921162  0.99211658 0.99211487 0.99211551]]


In [15]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    # how much did we miss?
    l2_error = y - l2
    l2_delta = l2_error*nonlin(l2,deriv=True)
    
    l1_error = l2_delta.dot(syn1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,deriv=True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    syn1 += np.dot(l1.T,l2_delta)


print ("Output After Training:")
print (l2)

Output After Training:
[[0.00503509]
 [0.00400015]
 [0.99519886]
 [0.99462398]]


In [11]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,4)) - 1
syn2 = 2*np.random.random((4,1)) - 1

for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l3 = nonlin(np.dot(l2,syn2))
    
    # how much did we miss?
    l3_error = y - l3
    l3_delta = l3_error*nonlin(l3,deriv=True)
    
    l2_error = l3_delta.dot(syn2.T)
    
    l2_delta = l2_error * nonlin(l2,deriv=True)
    
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    syn1 += np.dot(l1.T,l2_delta)
    syn2 += np.dot(l2.T,l3_delta)
print ("Output After Training:")
print (l3)

Output After Training:
[[0.00443046]
 [0.00335398]
 [0.99531586]
 [0.99477531]]


In [12]:
# input dataset
X = np.array([  [0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])

# output dataset            
yMultiple = np.array([[0,0,1,1], [1,0,0,1]]).T

# initialize weights randomly with mean 0
syn_0 = 2*np.random.random((3,4)) - 1
syn_1 = 2*np.random.random((4,2)) - 1

for iter in range(10000):
    # forward propagation
    l_0 = X
    l_1 = nonlin(np.dot(l_0,syn_0))
    l_2 = nonlin(np.dot(l_1,syn_1))
    
    # how much did we miss?
    l2Error = yMultiple - l_2
    
    l2Delta = l2Error*nonlin(l_2,deriv=True)
    
    l1Error = l2Delta.dot(syn_1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1Delta = l1Error * nonlin(l_1,deriv=True)

    # update weights
    syn_0 += np.dot(l_0.T,l1Delta)
    syn_1 += np.dot(l_1.T,l2Delta)
print ("Output After Training:")
print (l_2)



Output After Training:
[[0.00458612 0.99192277]
 [0.00673242 0.00767814]
 [0.99468984 0.00913896]
 [0.99166709 0.99003917]]


In [13]:
# sinx regression function
def nonlinsin(x,deriv=False):
    if(deriv==True):
        return np.cos(x)
    return np.sin(x)

# initialize weights randomly with mean 0
syn_0 = 2*np.random.random((3,4)) - 1
syn_1 = 2*np.random.random((4,1)) - 1

for iter in range(10000):
    # forward propagation
    l_0 = X
    l_1 = nonlinsin(np.dot(l_0,syn_0))
    l_2 = nonlinsin(np.dot(l_1,syn_1))
    
    # how much did we miss?
    l2Error = y - l_2
    l2Delta = l2Error*nonlinsin(l_2,deriv=True)
    
    l1Error = l2Delta.dot(syn_1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1Delta = l1Error * nonlinsin(l_1,deriv=True)

    # update weights
    syn_0 += np.dot(l_0.T,l1Delta)
    syn_1 += np.dot(l_1.T,l2Delta)
print ("Output After Training:")
print (l_2)


Output After Training:
[[ 0.16209937]
 [-0.98724912]
 [ 0.08329829]
 [-0.08989709]]
